apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-pod
  template:
    metadata:
      labels:
        app: nginx-pod
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
          - containerPort: 80 # Internal container port
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        - name: html
          mountPath: /usr/share/nginx/html/404.html
          subPath: 404.html
        - name: conf
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
        - name: html
          configMap:
            name: nginx-configmap
        - name: conf
          configMap:
            name: nginx-configmap
