apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-fallback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-fallback
  template:
    metadata:
      labels:
        app: nginx-pod-fallback
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html/index.html
          subPath: index-fallback.html
      volumes:
      - name: html
        configMap:
          name: nginx-configmap
