apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx-svc-fallback
  name: nginx-svc-fallback
spec:
  ports:
  - name: nginx-svc-fallback
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-pod-fallback
  type: ClusterIP
